{
 "title": "Switch Core",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "description": "An administratively-assigned name for this managed node. By convention, this is the node's fully-qualified domain name. If the name is unknown, the value is the zero-length string",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch-core",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "The time (in hundredths of a second) since the network management portion of the system was last re-initialized",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch-core",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "table",
   "description": "The table of power supply status maintained by the environmental monitor card",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "power_description" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "power_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "power_source" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "description": "An entry in the ambient temperature status table, representing the status of the associated testpoint maintained by the environmental monitor",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "temp_description" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "temp_threshold" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan",
   "type": "table",
   "description": "An entry in the fan status table, representing the status of the associated fan maintained by the environmental monitor",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "coolers_description" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "coolers_condition" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "description": "A textual description of the entity. This value should include the full name and version identification of the system's hardware type, software operating-system, and networking software",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OS Version",
     "measurement": "switch-core",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "os_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "A table of overall CPU statistics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Physical Index: $tag_cpu_physical_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu_physical_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "An entry in the memory pool monitoring table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Memory Pool: $tag_memory_name",
     "query": "SELECT (last(\"memory_used\")/(last(\"memory_free\") + last(\"memory_used\")))*100 FROM \"switch-core\" WHERE $timeFilter GROUP BY time($__interval), \"memory_name\" fill(none)"
    }
   ]
  },
  {
   "title": "Data Rate (IN)",
   "type": "timeseries",
   "description": "The total number of octets received and transmitted on the interface, including framing characters. Discontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  NON_NEGATIVE_DERIVATIVE(last(\"ifInOctets\"), 1s) *8 FROM \"switch-core\" WHERE (\"ifOperStatus\"=1) AND $timeFilter GROUP BY time($__interval), \"ifName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rate (OUT)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  NON_NEGATIVE_DERIVATIVE(last(\"ifOutOctets\"), 1s) *8 FROM \"switch-core\" WHERE (\"ifOperStatus\"=1) AND $timeFilter GROUP BY time($__interval), \"ifName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Port Summary",
   "type": "table",
   "description": "An entry containing management information applicable to a particular interface",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"ip\") AS \"IP Address\", last(\"net_mask\") AS \"Net Mask\" FROM \"switch-core\" WHERE  $timeFilter GROUP BY \"ifIndex\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ifIndex" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "ifAlias" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1000000" ], "type": "math" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Stackwise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Switch Info",
   "type": "timeseries",
   "description": "A conceptual row in the cswSwitchInfoTable describing a switch information.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "alias": "Switch Number: $tag_switch_num_current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch_num_current" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "switch_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "switch_num_current" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "switch_role" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "switch_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "switch_power_budget" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "switch_power_allocated" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stack Port Info",
   "type": "timeseries",
   "description": "A conceptual row in the cswStackPortInfoTable. An entry contains information about a stackport",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "alias": "Stack Port: $tag_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "stack_port_oper_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "stack_port_neighbor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "stack_port_oper_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stack Power Info",
   "type": "table",
   "description": "An entry in the cswStackPowerInfoTable for each of the power stacks in a single data stack. This entry contains information regarding the power stack",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "index" ], "type": "tag" }
     ],
     "measurement": "switch-core",
     "select": [
      [
       { "params": [ "stack_power_mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "stack_power_type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "stack_power_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}